### ISSUE TITLE
渲染错误

### ISSUE THREAD

**Issue by dragon-archer** [MicrosoftDocs/WSL.zh-CN#11]
此页面的《安装Linux内核更新包》板块中的代码框中未能正常渲染html
（即，渲染为
1. &lt;span data-ttu-id="8efe6-111"&gt;运行上一步中下载的更新包。&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="8efe6-111"&gt;Run the update package downloaded in the previous step.&lt;/span&gt;&lt;/span&gt;
2. &lt;span data-ttu-id="8efe6-112"&gt;系统将提示你提供提升的权限，选择“是”以批准此安装。&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="8efe6-112"&gt;You will be prompted for elevated permissions, select ‘yes’ to approve this installation.&lt;/span&gt;&lt;/span&gt;
3. &lt;span data-ttu-id="8efe6-113"&gt;安装完成后，便可以开始使用 WSL2 了！&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="8efe6-113"&gt;Once the installation is complete, you are ready to begin using WSL2!&lt;/span&gt;&lt;/span&gt;

注：通过页面右上方的《编辑》按钮进入GitHub中预览的页面渲染正常

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [更新 WSL 2 Linux 内核](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dragon-archer** [comment]
补充：英文版文档无此问题，渲染正常

**Comment by srvbpigh** [comment]
Hello, @dragon-archer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@dragon-archer 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/WSL/issues/596。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
