### ISSUE TITLE
link missing

### ISSUE THREAD

**Issue by sysdl132** [MicrosoftDocs/WSL.zh-CN#13]
![image](https://user-images.githubusercontent.com/54708046/78097859-09be8100-7410-11ea-98fa-c77496d05b20.png)
![image](https://user-images.githubusercontent.com/54708046/78097868-12af5280-7410-11ea-9dde-b1ff96e389e1.png)
The following links are missing:
- [ ] ubuntu 18.04
- [ ] ubuntu 18.04 ARM
Link should is:
* https://aka.ms/wsl-ubuntu-1804
* https://aka.ms/wsl-ubuntu-1804-arm

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [手动下载适用于 Linux 的 Windows 子系统 (WSL) 发行版](https://docs.microsoft.com/zh-cn/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @sysdl132
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/windows/wsl/install-manual.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team

**Comment by sysdl132** [comment]
Thanks
