### ISSUE TITLE
wsl --set-default-version 2

### ISSUE THREAD

**Issue by alabohai** [MicrosoftDocs/WSL.zh-CN#16]
此命令无效，
PS C:\Windows\system32&gt; wsl --set-default-version 2
命令行选项无效: --set-default-version
版权所有 (c) Microsoft Corporation。保留所有权利。

用法: wsl.exe [参数] [选项...] [CommandLine]

用于运行 Linux 二进制文件的参数:

    如果未提供任何命令行，wsl.exe 将启动默认 shell。

    --exec, -e &lt;CommandLine&gt;
        在不使用默认 Linux shell 的情况下执行指定的命令。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [安装 WSL 2](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @alabohai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @alabohai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@alabohai 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/WSL/issues/625。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
