### ISSUE TITLE
how to set wsl2 install on any disk

### ISSUE THREAD

**Issue by chanRoot** [MicrosoftDocs/WSL.zh-CN#18]
I have 3 disk on my computer that disk c、d are ssd and e is hdd, and disk c is system ,d is storage many files about project and some servers such as mid-soft of apache、vmware vitual disk, and e put some other things , I know ubuntu   is bigger more than 2 g  size and  store also has other linux system like centos、arch.eg..
So i want to know how to install wsl2 on my disk d not c.

**Comment by srvbpigh** [comment]
Hello, @chanRoot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by acooler15** [comment]
导出，再导入[wsl、wsl2 导出迁移](https://www.jianshu.com/p/d51df75e1b9e)

**Comment by CeciAc** [comment]
Hello, @chanRoot 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion here: https://github.com/Microsoft/WSL/issues

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
