### ISSUE TITLE
The marked part should not be translated

### ISSUE THREAD

**Issue by acooler15** [MicrosoftDocs/WSL.zh-CN#19]
![Snipaste_2020-05-12_00-33-32](https://user-images.githubusercontent.com/19186382/81586828-b9f8af80-93e8-11ea-977f-ebdada7e2000.png)
![Snipaste_2020-05-12_00-33-53](https://user-images.githubusercontent.com/19186382/81586835-bc5b0980-93e8-11ea-9b90-5f1d112f72e2.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [管理 Linux 分发版](https://docs.microsoft.com/zh-cn/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @acooler15
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@acooler15  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/windows/wsl/wsl-config#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
