### ISSUE TITLE
How to uninstall it By Windows Server Installation Guide

### ISSUE THREAD

**Issue by JustForUsing** [MicrosoftDocs/WSL.zh-CN#20]
I successfully installed WSL in this way, but how to uninstall it? 
The operation about deleted the installation folder directly make me can't open the shell after reinstallation,
It flash back by click the launcher directly,
It show "为此分发实施适用于 Linux 的 Windows 子系统文件系统的一次性升级...拒绝访问。", by powershell command,
It's useless to clean registry
So shouldn't there be an uninstall script in the package?  0.0..

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [在 Windows Server 上安装 Linux 子系统](https://docs.microsoft.com/zh-cn/windows/wsl/install-on-server#feedback)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @JustForUsing
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JustForUsing** [comment]
I found a solution，do follow two steps 
wslconfig /list                            
//Powershell executes this command to view a list of registered subsystems
wslconfig /u Ubuntu-18.04                 //注销已删除文件夹的系统，此时已经能安装了

**Comment by CeciAc** [comment]
Hello, @JustForUsing 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
