### ISSUE TITLE
代码显示错误

### ISSUE THREAD

**Issue by hyzx86** [MicrosoftDocs/WSL.zh-CN#21]
代码显示错误

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [更新 WSL 2 Linux 内核](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @hyzx86
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@hyzx86

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by hyzx86** [comment]
我记得那个问题是一段示例代码呈现为html 代码了
我又点了那几个页面，

现在看来似乎已经好了


---原始邮件---
发件人: "Cecilia Acevedo"<notifications@github.com&gt;
发送时间: 2020年5月19日(周二) 凌晨1:34
收件人: "MicrosoftDocs/WSL.zh-CN"<WSL.zh-CN@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Tony Han"<huarui2219@qq.com&gt;;
主题: Re: [MicrosoftDocs/WSL.zh-CN] 代码显示错误 (#21)




 
你好，@hyzx86
 
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
 
顺祝商祺！
 
Microsoft DOCS 国际团队

**Comment by V-vafune** [comment]
你好，@hyzx86  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  
Microsoft DOCS International Team
