### ISSUE TITLE
链接（https://aka.ms/wsl2kernel）定向可能有问题

### ISSUE THREAD

**Issue by wangfengchen** [MicrosoftDocs/WSL.zh-CN#38]
"跟随链接（https://aka.ms/wsl2kernel），在文档中安装来自该页面的 MSI"
点击以上超链接以后又重新回到了当前页面,没法下载需要的msi文件.导致无法更新到wsl2

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [在 Windows 10 上安装适用于 Linux 的 Windows 子系统 (WSL)](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by yiwozhisha** [comment]
我也发现此问题，可尝试通过https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi该链接直接下载

**Comment by tobieas** [comment]
这个问题英文版页面就是正常的，中文就bug了
https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

**Comment by wangfengchen** [comment]
> 我也发现此问题，可尝试通过https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi该链接直接下载

谢谢

**Comment by wangfengchen** [comment]
> 这个问题英文版页面就是正常的，中文就bug了
> 
> https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

谢谢
