### ISSUE TITLE
跨系统磁盘访问速度太慢

### ISSUE THREAD

**Issue by stlswm** [MicrosoftDocs/WSL.zh-CN#8]
要是能解决跨系统的磁盘访问速度问题，那wsl2将会是很好的产品。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 常见问题](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-faq#feedback)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @stlswm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@stlswm

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。

如果你有任何与文档相关的反馈，请通过此渠道进行记录。

我们非常感谢你对我们的文章的贡献。

Microsoft DOCS 国际团队
